//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int id { get; set; }
        public int müsteriId { get; set; }
        public int tutar { get; set; }
        public System.DateTime tarih { get; set; }
        public int durumu { get; set; }
        public bool aktifMi { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
